---
title: "Data Cleaning"
output: html_notebook
---

# 1. Required packages installed
```{r}
library(tidyverse)
library(dplyr)
library(anytime) #convert UNIX epoch to date format
library(eeptools) #calculate age of pipes
library(ggplot2)
library(lubridate)
library(car)
library(visdat) # visualize missing values
```

# 2. Data Exploration
## 2.1 Data import and join
```{r}
# Import the data sets
ins <- read.csv("C:/Users/Claire/Desktop/Mott MacDonald/inspection_data.csv")
pip <- read.csv("C:/Users/Claire/Desktop/Mott MacDonald/pipe_data2.csv")
gis <- read.csv("C:/Users/Claire/Desktop/Mott MacDonald/GIS_SW_PIPES.csv")
# Only select the columns we need from three data sets
# Inspection data 
glimpse(ins)
ins_new <- subset(ins, select = c(assetid, Inspection.Date,
                                  CCTV...StructuralMeanGrade,
                                  CCTV...StructuralPeakGrade,
                                  CCTV...ServiceGrade,
                                  CCTV...ServicePeakGrade,
                                  CCTV...ServiceMeanGrade))
# Pipe data from the company's system
glimpse(pip)
# GIS stormwater data 
#structure
glimpse(gis)
# Choose those columns we are interested
gis_sw <- subset(gis, 
                 select = c(SW_OBJECTTYPE, SW_SAP_ID,
                            SW_CAPACITY_DEV_SCENARIO,
                            SW_CRE, SW_DEPTH_DOWNSTREAM_M,
                            SW_DEPTH_UPSTREAM_M, SW_DIAMETER_MM,
                            SW_GRADIENT_PC, SW_INSTALLATION_DATE,
                            SW_INVERT_LEVEL_DOWNSTREAM_M,
                            SW_INVERT_LEVEL_DOWNSTREAM_M,
                            SW_IS_LINED, SW_LENGTH_GIS_M,
                            SW_MATERIAL, SW_SHAPE, SW_GIS_ID))
glimpse(gis_sw)

# Merging three data frames using left join
join1 <- left_join(ins_new, pip, 
                  by = c("assetid" = "assetid"))
data <- left_join(join1, gis_sw,
                  by = c("sap_id" = "SW_SAP_ID"))
# Structure of the result 
glimpse(data)
# Observations of top 6 rows
head(data)
# Summary of the data set
summary(data)
# Check percentage of missing values for each column
(colMeans(is.na(data)))*100
# Drop three columns with more than 80% missing values
df <- subset(data, select = -c(downstream_depth, 
                                 upstream_depth, 
                                 likelihood_of_failure))
glimpse(df)
```

## 2.2 Pipe Age
```{r}
# Column install_date and Inspection.Date
# Change the values of install_date into date format
df$install_date <- anydate(df$install_date)
# Change the datetime format of inspection date
df$inspection_date <- dmy_hm(df$Inspection.Date)
# Only grab the date without time from the inspection date
df$inspection_date <- as.Date(df$inspection_date)
# Check any missing values 
table(is.na(df$install_date))
table(is.na(df$inspection_date))
# Remove rows with missing values
df <- df %>% 
  tidyr::drop_na(c(install_date, inspection_date))
# Calculate the difference between install date and inspection date to get pipe age.
df$years <- trunc((df$install_date %--% df$inspection_date)/years(1))
# Count the number of each value in the year column
df %>%
  group_by(years) %>%
  summarize(number_rows = n())
# drop rows with negative values
df1 <- df %>% filter(years >= 0)

# Visualize the column years(age at time of inspection)
hist(df1$years,
     main="Histogram for Pipe Age",
     xlab="Age")
hist(df1$install_date,breaks=50,
     main="Histogram for Installation Year",
     xlab="Year")
```
## 2.3 Pipe Material
```{r}
glimpse(df1)
# Column GIS SW_MATERIAL
df1 %>%
  group_by(SW_MATERIAL) %>%
  summarise(number = n())
# Remove rows with missing values
df1 <- subset(df1, SW_MATERIAL != "")
df2 <- df1 %>% 
  tidyr::drop_na(SW_MATERIAL)

# Replace the pipe materials whose count number is less than 100 with "OTHR".
df2$SW_MATERIAL <- with(df2, 
                ave(SW_MATERIAL, SW_MATERIAL,
                FUN = function(i) replace(i, length(i) <100, 'OTHR')))
# Visualize the column
ggplot(df2, aes(x=SW_MATERIAL)) +
  geom_bar() +
  ggtitle("Plot of Pipe Materials") +
  xlab("Pipe Materials")

```

## 2.4 Pipe Rehabilitation
```{r}
# Column SW_IS_LINED
# Pipes with rehabilitation need to be excluded in this data set as it will affect the results.
table(is.na(df2$SW_IS_LINED))
# There is no missing values
df2 %>% 
  group_by(SW_IS_LINED) %>%
  summarise(n = n())
# Select those pipes have not been lined
df3 <- df2 %>% filter(SW_IS_LINED != "Y")
```


## 2.5 Pipe Length(m)
```{r}
# Column SW_LENGTH_GIS_M
table(is.na(df3$SW_LENGTH_GIS_M)) # no missing values
df3 %>%
  group_by(SW_LENGTH_GIS_M) %>%
  summarise(n = n())
# Boxplot to check any outliers of pipe length
boxplot(df3$SW_LENGTH_GIS_M)
# Get Q1, Q3 and interquartile range for values
Q1 <- quantile(df3$SW_LENGTH_GIS_M, .25)
Q3 <- quantile(df3$SW_LENGTH_GIS_M, .75)
IQR <- IQR(df3$SW_LENGTH_GIS_M)
# Remove outliers
df4 <- subset(df3, df3$SW_LENGTH_GIS_M > (Q1 - 1.5*IQR) &
                df3$SW_LENGTH_GIS_M < (Q3 + 1.5*IQR))
# Scatter plot of pipe length
ggplot(df4, aes(x=inspection_date, y=SW_LENGTH_GIS_M)) + 
  geom_point()
# descriptive summary of pipe length
summary(df4$SW_LENGTH_GIS_M)
# Structure of df4
glimpse(df4)
```

## 2.6 Pipe Diameter(mm)
```{r}
# Column SW_DIAMETER_MM
# check any NAs
table(is.na(df4$SW_DIAMETER_MM))
# Drop missing values
df4 <- df4 %>% drop_na(SW_DIAMETER_MM)
# Check number of each value in the column
df4 %>% count(SW_DIAMETER_MM)
# Remove values of "0" and "4" as they don't make sense
df4 <- df4 %>% filter(SW_DIAMETER_MM >= 100)
# boxplot 
boxplot(df4$SW_DIAMETER_MM)
# Get Q1, Q3 and interquartile range for values
#Q1_d <- quantile(df4$SW_DIAMETER_MM, .25)
#Q3_d <- quantile(df4$SW_DIAMETER_MM, .75)
#IQR_d <- IQR(df4$SW_DIAMETER_MM)
# Remove outliers
df5 <- subset(df4, df4$SW_DIAMETER_MM >= 100 &
                df4$SW_DIAMETER_MM <= 2000)
boxplot(df5$SW_DIAMETER_MM)
summary(df5$SW_DIAMETER_MM)

```

## 2.7 Pipe Shape
```{r}
# Column SW_SHAPE
# Based on Table2.11 from 3rd edition of NZ Pipi Inspection Manual,
# there are 7 categories of pipe shape, CP (Circular Pipe), ES(Egg-Shaped),OS(Oval-Shaped), RB(Rectangular Box), SB(Square Box), US(U-Shaped), XX(Others).
table(is.na(df5$SW_SHAPE)) # no NAs
df5 %>% 
  group_by(SW_SHAPE) %>%
  summarise(n=n())

```


```{r}
# Column SW_CRE
sw1 %>% 
  group_by(SW_CRE) %>%
  summarise(number = n())
# Remove rows of NA 
sw2 <- subset(sw1, SW_CRE != "")
# Plots
ggplot(sw2, aes(SW_CRE)) +
  geom_bar() +
  theme(axis.text.x=element_text(angle=45))
```






```{r}
# Column upstream_invert, downstream_invert and pipe_length
# to calculate pipe slope
df4 %>%
  group_by(upstream_invert) %>%
  summarise(number_count = n())
df4 <- df4 %>%
  group_by(downstream_invert) %>%
  summarise(number_count = n()) 
df5 <- df4 %>% filter(upstream_invert >0 & downstream_invert >0)
df5 %>%
  group_by(pipe_length) %>%
  summarise(number_count = n())
df5 <- df5 %>% 
  mutate(slope = (upstream_invert - downstream_invert)/pipe_length*100)
df5 %>% count(slope) 
df5 %>% filter(slope >= 0)

hist(df5$slope)
```
```{r}
df4 %>% count(jointspacing_m)
```

